version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - frontend-build:/usr/share/nginx/html

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/martinbullman:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - nginx

volumes:
  pg-data:
  frontend-build:
