name: Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: v20.10.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Artifacts
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: |
          npm install
          npm build
          cp .env .output/server/.env
          tar czf "${{ GITHUB_SHA }}".tar.gz .output
      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ${{ github.sha }}.tar.gz
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifacts@v3
        with:
          name: app-artifacts
      - name: Deploy Artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          target: /home/ubuntu
