# GitHub action to deploy MartinBullmanApp backend.
name: deploy-backend

on:
  # trigger workflow on pushes to the main branch or pull requests targeting the main branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # set environment variables for node.js version and github context values.
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]
    steps:
      # step 1: checkout the code from the repository.
      - name: Checkout Code
        uses: actions/checkout@v4

      # step2: setup python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # step 3: installed the python dependencies.
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # step 4: run the pylint.
      - name: Run Pylint
        working-directory: ./backend/martinbullman
        run: |
          pylint $(git ls-files '*.py')

  test:
    # build job runs on the latest ubuntu environment.
    runs-on: ubuntu-latest

    steps:
      # step 1: checkout the code from the repository.
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: ./backend/martinbullman
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt    

      - name: Run Tests
        working-directory: ./backend/martinbullman
        run: |
          python manage.py test    


  build:
    # build job runs on the latest ubuntu environment.
    needs: test
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/martinbullman/requirements.txt
    - name: Run Tests

      run: |
        cd backend/martinbullman/
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_FROM_ADDRESS }}
        EMAIL_FROM_NAME: ${{secrets.EMAIL_FROM_NAME}}

        MAILJET_API_KEY: ${{secrets.MAILJET_API_KEY}}
        MAILJET_API_SECRET: ${{secrets.MAILJET_API_SECRET}}

        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
