name: Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Application
        working-directory: ./frontend
        run: npm run build

      - name: Archive Artifacts
        working-directory: ./frontend/
        run: tar czf ../"${{ env.GITHUB_SHA }}".tar.gz .output

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ${{ env.GITHUB_SHA }}.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts

      - name: Deploy Artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          target: /home/ubuntu
          source: ./downloaded-artifacts/${{ env.GITHUB_SHA }}.tar.gz



#
#    - name: Test SSH Connection
#      run: ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/github_actions ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "echo Connection Successful"
#
#    - name: Install Dependencies
#      working-directory: ./frontend/
#      run: npm install
#
#    - name: Build Application
#      working-directory: ./frontend/
#      run: npm run build
#
#    - name: Archive Build Artifacts
#      working-directory: ./frontend/
#      run: zip -r build.zip .output
#
#    - name: Transfer Build Artifacts to Lightsail
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.LIGHTSAIL_HOST }}
#        username: ${{ secrets.LIGHTSAIL_USER }}
#        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
#        source: ./frontend/build.zip
#        target: /home/ubuntu/
#
#    - name: Debug File Location
#      uses: appleboy/ssh-action@v0.1.8
#      with:
#        host: ${{ secrets.LIGHTSAIL_HOST }}
#        username: ubuntu
#        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
#        script: |
#          ls -l /home/ubuntu
#
#    - name: Deploy Application
#      uses: appleboy/ssh-action@v0.1.8
#      with:
#        host: ${{ secrets.LIGHTSAIL_HOST }}
#        username: ${{ secrets.LIGHTSAIL_USER }}
#        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
#        script: |
#          unzip -o /home/ubuntu/build.zip -d /home/ubuntu
#          cd /home/ubuntu
#          npm install --production
#          pm2 restart all
