name: Build and Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: List project files
      run: ls -la

    - name: Add SSH key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan "${{ secrets.LIGHTSAIL_HOST }}" >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions

    - name: Test SSH Connection
      run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_SSH_KEY }} ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "echo Connection Successful"

    - name: Install Dependencies
      working-directory: ./frontend/
      run: npm install

    - name: Build Application
      working-directory: ./frontend/
      run: npm run build

    - name: Archive Build Artifacts
      working-directory: ./frontend/
      run: zip -r build.zip .output public package.json

    - name: Transfer Build Artifacts to Lightsail
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: build.zip
        target: /home/ubuntu/build.zip

    - name: Deploy Application
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          unzip -o /home/ubuntu/build.zip -d /home/ubuntu/app
          cd /home/ubuntu/app
          npm install --production
          pm2 restart all
