name: Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Application
        working-directory: ./frontend
        run: npm run build

      - name: Archive Artifacts
        working-directory: ./frontend/
        run: tar czf ../"${{ env.GITHUB_SHA }}".tar.gz .output

      - name: List Build Output
        run: ls -lah

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: ${{ env.GITHUB_SHA }}.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts
          path: ./downloaded-artifacts

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |  
          mkdir -p /home/runner/.ssh  
          ssh-keyscan "${{ secrets.LIGHTSAIL_HOST }}" >> /home/runner/.ssh/known_hosts  
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > /home/runner/.ssh/github_actions  
          chmod 600 /home/runner/.ssh/github_actions  
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null  
          ssh-add /home/runner/.ssh/github_actions      

      - name: Deploy Artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          target: /home/ubuntu
          source: ./downloaded-artifacts/${{ env.GITHUB_SHA }}.tar.gz

      - name: Extract Artifacts
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            set -e # Exit on any command failure
            mkdir -p "/home/ubuntu/releases/${{ env.GITHUB_SHA }}"
            tar xzf "/home/ubuntu/downloaded-artifacts/${{ env.GITHUB_SHA }}.tar.gz" -C "/home/ubuntu/MartinBullmanApp/frontend"
            cp -r "/home/ubuntu/MartinBullmanApp/frontend/.output" "/home/ubuntu/releases/${{ env.GITHUB_SHA }}"
            
            # Ensure Node.js environment is loaded
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20.13.1
            
            /home/ubuntu/.nvm/versions/node/v20.13.1/bin/pm2 restart all
