name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/martinbullman/requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: rn(20g7%1j-^h0m#6nr1qsppkqq__io2nt^kngiv!#ph_1$wce
      run: |
        python backend/martinbullman/manage.py test
